# Generated by Django 2.2.10 on 2021-11-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='is_right_answer',
        ),
    ]
